### PR TITLE
fix #7 and fix #8

### LINKED ISSUE #7: [FEATURE] Add basic pages
Add basic pages scaffold
- Home
- Login

### LINKED ISSUE #8: [FEATURE] Add Basic Routes
Routes
- home
- login
- Page not found 404

### PR DESCRIPTION
**Pull request by judd-gnizama**
fix #7 and fix #8 - added basic pages and added routes. Removed test fetch

### CODE REVIEW

**Review by famasboy888 — CHANGES_REQUESTED** [review]
@judd-gnizama 
Something broke in the packages in vercel, I cant merge for now:
image

Vercel output:
image

Ill try this fix:
https://stackoverflow.com/questions/62378045/how-to-fix-next-js-vercel-deployment-module-not-found-error

**Comment by judd-gnizama** [comment]
Ohh. I think I know na the problem. 
I mistakenly installed the react-router-dom in the backend. Should have been in the frontend folder.

Will try to remove react-router-dom from backend then install in frontend

**Review by famasboy888 — APPROVED** [review]
All working @judd-gnizama

**Comment by judd-gnizama** [comment]
Nice one!

**Pull request merged**
